version: '2'

# 本地测试版本，和测试版本不同的地方volumes和nginx，全部挂载到local_mount_path
services:

  imvectorclient:
    image: registry.cn-shenzhen.aliyuncs.com/imvector/imvectorclient
    volumes:
      # 日志直接放和生产同一个目录下面
      - /usr/local/imvector/logs:/tmp/logs
    # 指定环境变量
    environment:
      PARAMS: "-Dlogging.config=classpath:logback-dev.xml"
    mem_limit: 800M
    memswap_limit: 1000M
    network_mode: "host"

